# Generated by Django 5.2 on 2025-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
