# Generated by Django 5.2 on 2025-06-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_dmmessage_receiver_remove_dmmessage_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt',
            name='author',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='created_at',
        ),
    ]
