# Generated by Django 5.2.4 on 2025-07-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
